/** Auto Generated definitions */
#define NFORMULAS (14)
#define NSTRUCT (6)
#define NBUFLEN (13)
#define FORM_DELAY (0)
#define POLICY (13)
#define STACK_DEPTH (5)
#define MASK_time (1<<(0))
#define MASK_x (1<<(1))
#define MASK_p (1<<(2))
#define MASK_q (1<<(3))
#define MASK_r (1<<(4))
#define MASK_t (1<<(5))
