/** Auto Generated definitions */
#define NFORMULAS (7)
#define NSTRUCT (1)
#define NBUFLEN (8)
#define FORM_DELAY (0)
#define POLICY (6)
#define STACK_DEPTH (6)
#define MASK_time (1<<(0))
#define MASK_a (1<<(1))
#define MASK_b (1<<(2))
